# Direwolf.conf file generated: 2026-05-16 13:06:37.211843
ADEVICE null null
CHANNEL 0
MYCALL KJ0RE-10
IGSERVER noam.aprs2.net
IGLOGIN KJ0RE-10 19962
PBEACON sendto=IG delay=0:30 every=10 symbol="igate" overlay=R lat=43.7113 long=-98.008 comment="Docker Direwolf + ka9q"
LATITUDE 43.7113
LONGITUDE -98.008
