# Direwolf.conf file generated: 2026-05-09 15:49:51.811707
ADEVICE null null
CHANNEL 0
MYCALL TEST-10
IGSERVER noam.aprs2.net
IGLOGIN TEST-10 12345
PBEACON sendto=IG delay=0:30 every=10 symbol="igate" overlay=R lat=0 long=0 comment="Docker Direwolf + RTL-SDR"
