# Use STDIN from SDR
ADEVICE stdin null
ARATE 24000
ACHANNELS 1

CHANNEL 0
MYCALL KD2EAT
MODEM 1200

# KISS/AGW - maybe later
#AGWPORT 8000
#KISSPORT 8001

# It is sometimes possible to recover frames with a bad FCS.
# This applies to all channels.  
#
#	0  [NONE] - Don't try to repair.
#	1  [SINGLE] - Attempt to fix single bit error.  (default)
#	2  [DOUBLE] - Also attempt to fix two adjacent bits.
#	... see User Guide for more values and in-depth discussion.
#

#FIX_BITS 0


# INTERNET GATEWAY
IGSERVER noam.aprs2.net
IGLOGIN KJ0RE 19962
IGTXLIMIT 6 10
LOGFILE /app/logs/direwolf.log

