# Start command:
# docker run -it --rm --device=/dev/bus/usb -v ~/testaprs/rtl-aprs-igate/station.conf:/station.conf:ro rtl-aprs-igate:latest
# Build command: docker build -t rtl-aprs-igate-branch https://github.com/bklofas/rtl-aprs-igate.git#addka9q
# r
  
# rtl-aprs-igate Station Configuration File
#
# Copy this file to station.conf and modify as required.
#
##################
# RTL-SDR Settings
##################
[rtl_fm]

# If using ka9q or a source other than rtl-sdr set it here.
# Options: ka9q, RTLSDR, sound
# Use device_idx below to set the data stream.
# Use frequency to set correct receive frequency but it will not set ka9q.
# Use ka9q pcm commands to set entire ka9q command>
# i.e. pcmrecord@127.0.0.1:5004 or pcmrecord --stdout --ssrc 123456-1 \
#    fm-pcm.local |sox -t wav -highpass 200
# DO NOT put quotes around entries!

#source = RTLSDR
# source = ka9q
source = sound

# pcm_command = fm-pcm.local |sox -t wav -highpass 200

# APRS frequency (in MHz)
#   North America: 144.39
#   Europe: 144.80
#   Australia: 145.175


# frequency = 144.39
frequency = 432.900

# Device Index / Serial Number
#    If using a single RTLSDR, set this value to 0
#    If using multiple SDRs, you MUST allocate each SDR a unique serial string >
#    I encourage using "SDR00002" or similar incrementing string
#    The serial number must NOT be 00000000 or 00000001, as this causes big con>
#    i.e. to set the serial number of a (single) connected RTLSDR: rtl_eeprom ->

device_idx = 0

# Frequency Correction (part-per-million offset)
ppm = 0

# Bias Tee - Enable the bias tee in the RTLSDR v3 and v4 Dongles. (True/False)
bias = False

# SDR Gain Setting
#    Gain settings can generally range between 0dB and 40dB depending on the tu>
#    Run rtl_test to confirm what gain settings are available, or use a value o>
#    Note that this is an overall gain value, not an individual mixer/tuner gai>
gain = -1

###################
# Direwolf Settings
###################
[direwolf]

# My callsign
mycall = KJ0RE

# Secondary Station Identifier for your igate station
# This is the -N after your callsign, usually 10 for Igates
# See https://www.aprs.org/aprs11/SSIDs.txt
ssid = 10

# adevice = plughw:3,1
adevice = null null

# Tier 2 internet server.
# Use one of these regional rotate addresses:
#     noam.aprs2.net           - for North America
#     soam.aprs2.net          - for South America
#     euro.aprs2.net          - for Europe and Africa
#     asia.aprs2.net           - for Asia
#     aunz.aprs2.net          - for Oceania
igserver = noam.aprs2.net

# APRS passcode (tied to your callsign)
# https://apps.magicbug.co.uk/passcode/
igpasscode = 12345

# Send your IGate location to the APRS network
pbeacon= true

# Beacon delay
beacondelay = 0:30

# Beacon every X minutes
beaconevery = 10

# Beacon symbol
# Can be either from the APRS symbols list:
# https://www.aprs.org/symbols/symbolsX.txt
# Or can be a text substring of the description
beaconsymbol = igate

# Latitude of your receive station
lat = 0

# Longitude of your receive station
long = 0

# Comment about your station. Note that this only shows on your beacon.
igcomment = Docker Direwolf + RTL-SDR

# You might want to apply a filter for what packets will be obtained from the server.
# Read about filters here:  http://www.aprs-is.net/javAPRSFilter.aspx
igfilter = 
